Fix Segmetation faults on Ubuntu and Ruby 2.4
draftcode/extreme_timeout pull request #6
Opened 2017-02-23 03:39 UTC by eitoball

It seems that extreme_timeout does not behave correctly (raises Segmetation Faults) in ruby 2.4 on Ubuntu platform. This PR should fix such issue.

I added a Dockerfile (`Dockerfile.ruby-2.4`) in this PR to test. You can run spec like the following.

```
$ docker build -f Dockerfile.ruby-2.4 .
...
Removing intermediate container 123456abcdef
Successfully built 111111aaaaaa
$ docker run 111111aaaaaa
Run options: include {:focus=>true}
...
Finished in 8.04 seconds (files took 0.06717 seconds to load)
10 examples, 0 failures

Randomized with seed 52811
```

2017-02-23 09:21 UTC, draftcode commented
I'm not sure why the optimization flag could have changed the behavior. Can you reproduce this constantly?

2017-02-23 09:36 UTC, draftcode commented
Oh. Looks like I can reproduce this bug by removing "static". Huh.

2017-02-23 09:39 UTC, eitoball commented
> I'm not sure why the optimization flag could have changed the behavior. 

Changing optimization flag is just precaution. I think that `static` flag on line 85 of  `ext/extreme_timeout/extreme_timeout.c` fixes this issue.

> Can you reproduce this constantly?

Yes, with `Dockerfile.ruby-2.4'

2017-02-23 23:10 UTC, draftcode commented
Looks like the exposed name "timeout" causes something. Changing the name also fixes the issue. Can you add this explanation somewhere?

2017-02-24 03:25 UTC, eitoball commented
> Looks like the exposed name "timeout" causes something. Changing the name also fixes the issue. 

Yes, seems like that. But, I don't know why...

> Can you add this explanation somewhere?

Will do.

2017-03-02 05:50 UTC, draftcode commented
Sorry. I've been sick this week. Can you wait until this weekend?

2017-03-02 06:05 UTC, eitoball commented
Of course, I can wait. Take care.

2017-03-09 04:32 UTC, draftcode commented
OK. Please make a separate PR for tests and others. Leave only the last commit and 'static' change in this PR. I'll merge both.

2017-03-09 05:13 UTC, eitoball commented
> Leave only the last commit and 'static' change in this PR.

Done.

> Please make a separate PR for tests and others.

Working on it. Thx.

2017-03-09 05:14 UTC, draftcode requested changes

2017-03-09 05:14 UTC, draftcode commented on ext/extreme_timeout/extreme_timeout.c
> +    int exitcode_ = 1, state;
This rename is not related to the fix.

2017-03-09 05:14 UTC, draftcode commented on ext/extreme_timeout/extconf.rb
> +CONFIG['optflags'] = '-O0'
This is also not related.

2017-03-09 05:22 UTC, draftcode requested changes

2017-03-09 05:22 UTC, draftcode commented on ext/extreme_timeout/extreme_timeout.c
> + * XXX: Exposing this function name "timeout" caused segmentation
s/XXX/NOTE/

2017-03-09 05:22 UTC, draftcode commented on ext/extreme_timeout/extreme_timeout.c
> + * fault in some environment (See PR #6). Instead of adding "static"
The sentence "Instead of ..." is not needed. Adding a note about exposure is enough.

2017-03-09 07:27 UTC, eitoball commented on ext/extreme_timeout/extreme_timeout.c
> +    int exitcode_ = 1, state;
Reverted. FYI, `exitcode` is also defined as global variable in line 12.

2017-03-09 07:27 UTC, eitoball commented on ext/extreme_timeout/extconf.rb
> +CONFIG['optflags'] = '-O0'
Removed.

2017-03-09 07:29 UTC, eitoball commented on ext/extreme_timeout/extreme_timeout.c
> + * XXX: Exposing this function name "timeout" caused segmentation
OK. FYI, http://wiki.c2.com/?FixmeComment

2017-03-09 07:29 UTC, eitoball commented on ext/extreme_timeout/extreme_timeout.c
> + * fault in some environment (See PR #6). Instead of adding "static"
OK, removed.

2017-03-09 07:31 UTC, eitoball commented
Thank you for reviewing. I think that I fixed all change requests.

2017-03-12 22:39 UTC, merged